
Bioconductor:
    CodingStyle:
      Indentation: "Use 4 spaces for indenting. No tabs."
      LineLength: "No lines longer than 80 characters."
      Variable:
        Name: "Use camelCaps: initial lowercase, then alternate case between words."
      Function:
        Name: "Use camelCaps: initial lower case, then alternate case between words."
        DoNotUse: "Do not use ‘.’ (in the S3 class system, some(x) where x is class A will dispatch to some.A)."
        Prefix: "Prefix non-exported functions with a ‘.’."
      Class:
        Name: "Use CamelCaps: initial upper case, then alternate case between words."
      File:
        RCode:
          Name:
            Prefix: "Use the prefix ‘methods-‘ for S4 class methods, e.g., ‘methods-coverage.R’. Generic definitions can be listed in a single file, ‘AllGenerics.R’, and class definitions in ‘AllClasses.R’."
            Extension: "Filename extension for R code should be ‘.R’."
        man:
          Name:
            Extension: "Filename extension for man pages should be ‘.Rd’."
      UseOfSpace:
        AfterComma: "Always use space after a comma. This: a, b, c."
        AroundEqualOperator: "No space around “=” when using named arguments to functions. This: somefunc(a=1, b=2)"
        AroundBinaryOperator: "Space around all binary operators: a == b."
    build:
      Command: R build .
    check:
      Guidelines: http://r-pkgs.had.co.nz/check.html
      Checks:
          Metadata:
          Package structure:
          Description:
          Namespace:
          R code:
          Data:
          Documentation:
          Demos:
          Compiled code:
          Tests:
          Vignettes:
    BiocCheck:
      Guidelines: http://bioconductor.org/packages/release/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#bioccheck
      Checks:
        Dependency Checks:
        Deprecated Package Checks:
        Remotes Usage Check:
        Version Checks:
        Package and File Size Check:
        biocViews Checks:
        Build System Compatibility Checks:
        NAMESPACE checks:
        Vignette Checks:
        Checking Install or Update Package Calls in R code:
        Coding Practices Checks:
        Function length checking:
        man page checking:
        NEWS checks:
        Unit Test Checks:
        Formatting checks:
        Duplication checks:
        bioc-devel Subscription Check:
        Support Site Registration Check:
