repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-added-large-files
    -   id: end-of-file-fixer
        exclude: '\.Rd' # sometimes roxygen fails to generate EOF blank line.
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.2
    hooks:
    #-   id: lintr
    # args: [--warn_only]
    # verbose: true
    #-   id: style-files
    #    args: [--style_pkg=styler, --style_fun=tidyverse_style]
    -   id: roxygenize
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: use-tidy-description
    -   id: spell-check
        exclude: >
          (?x)^(
          data/.*|
          (.*/|)\.Rprofile|
          (.*/|)\.Renviron|
          (.*/|)\.gitignore|
          (.*/|)NAMESPACE|
          (.*/|)WORDLIST|
          (.*/|)\.travis.yml|
          (.*/|)appveyor.yml|
          (.*/|)\.Rbuildignore|
          (.*/|)\.pre-commit-.*|
          .*\.[rR]|
          .*\.Rproj|
          .*\.py|
          .*\.feather|
          .*\.rds|
          .*\.Rds|
          .*\.sh|
          .*\.RData|
          .*\.RDS|
          .*\.png
          )$
