image:
  name: happyregistry.azurecr.io/methods/wes/somnibus:v1
  username: $USERNAME
  password: $PASSWORD
  email: $EMAIL

pipelines:
  pull-requests:
    '**': # on any branch
    - step:
        script:
          - R CMD build .
          # http://r-pkgs.had.co.nz/check.html
          - R CMD check --run-dontrun SOMNiBUS_0.1.0.tar.gz
          # http://bioconductor.org/packages/release/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html
          - R CMD BiocCheck --no-check-bioc-help SOMNiBUS_0.1.0.tar.gz
